/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostAdRouteImport } from './routes/post-ad'
import { Route as P2pRouteImport } from './routes/p2p'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmlKycRouteImport } from './routes/aml-kyc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAdRoute = PostAdRouteImport.update({
  id: '/post-ad',
  path: '/post-ad',
  getParentRoute: () => rootRouteImport,
} as any)
const P2pRoute = P2pRouteImport.update({
  id: '/p2p',
  path: '/p2p',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmlKycRoute = AmlKycRouteImport.update({
  id: '/aml-kyc',
  path: '/aml-kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/admin/deposits',
  path: '/admin/deposits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aml-kyc': typeof AmlKycRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/p2p': typeof P2pRoute
  '/post-ad': typeof PostAdRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/transfer': typeof TransferRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aml-kyc': typeof AmlKycRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/p2p': typeof P2pRoute
  '/post-ad': typeof PostAdRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/transfer': typeof TransferRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aml-kyc': typeof AmlKycRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/p2p': typeof P2pRoute
  '/post-ad': typeof PostAdRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/transfer': typeof TransferRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aml-kyc'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/deposit'
    | '/history'
    | '/orders'
    | '/p2p'
    | '/post-ad'
    | '/privacy'
    | '/profile'
    | '/risk'
    | '/terms'
    | '/transfer'
    | '/wallet'
    | '/withdraw'
    | '/admin/deposits'
    | '/admin/kyc'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aml-kyc'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/deposit'
    | '/history'
    | '/orders'
    | '/p2p'
    | '/post-ad'
    | '/privacy'
    | '/profile'
    | '/risk'
    | '/terms'
    | '/transfer'
    | '/wallet'
    | '/withdraw'
    | '/admin/deposits'
    | '/admin/kyc'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/aml-kyc'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/deposit'
    | '/history'
    | '/orders'
    | '/p2p'
    | '/post-ad'
    | '/privacy'
    | '/profile'
    | '/risk'
    | '/terms'
    | '/transfer'
    | '/wallet'
    | '/withdraw'
    | '/admin/deposits'
    | '/admin/kyc'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmlKycRoute: typeof AmlKycRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DepositRoute: typeof DepositRoute
  HistoryRoute: typeof HistoryRoute
  OrdersRoute: typeof OrdersRoute
  P2pRoute: typeof P2pRoute
  PostAdRoute: typeof PostAdRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RiskRoute: typeof RiskRoute
  TermsRoute: typeof TermsRoute
  TransferRoute: typeof TransferRoute
  WalletRoute: typeof WalletRoute
  WithdrawRoute: typeof WithdrawRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-ad': {
      id: '/post-ad'
      path: '/post-ad'
      fullPath: '/post-ad'
      preLoaderRoute: typeof PostAdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2p': {
      id: '/p2p'
      path: '/p2p'
      fullPath: '/p2p'
      preLoaderRoute: typeof P2pRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aml-kyc': {
      id: '/aml-kyc'
      path: '/aml-kyc'
      fullPath: '/aml-kyc'
      preLoaderRoute: typeof AmlKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/admin/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmlKycRoute: AmlKycRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DepositRoute: DepositRoute,
  HistoryRoute: HistoryRoute,
  OrdersRoute: OrdersRoute,
  P2pRoute: P2pRoute,
  PostAdRoute: PostAdRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RiskRoute: RiskRoute,
  TermsRoute: TermsRoute,
  TransferRoute: TransferRoute,
  WalletRoute: WalletRoute,
  WithdrawRoute: WithdrawRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
