/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostAdRouteImport } from './routes/post-ad'
import { Route as P2pRouteImport } from './routes/p2p'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAdRoute = PostAdRouteImport.update({
  id: '/post-ad',
  path: '/post-ad',
  getParentRoute: () => rootRouteImport,
} as any)
const P2pRoute = P2pRouteImport.update({
  id: '/p2p',
  path: '/p2p',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/p2p': typeof P2pRoute
  '/post-ad': typeof PostAdRoute
  '/profile': typeof ProfileRoute
  '/transfer': typeof TransferRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/p2p': typeof P2pRoute
  '/post-ad': typeof PostAdRoute
  '/profile': typeof ProfileRoute
  '/transfer': typeof TransferRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/p2p': typeof P2pRoute
  '/post-ad': typeof PostAdRoute
  '/profile': typeof ProfileRoute
  '/transfer': typeof TransferRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/deposit'
    | '/history'
    | '/orders'
    | '/p2p'
    | '/post-ad'
    | '/profile'
    | '/transfer'
    | '/wallet'
    | '/withdraw'
    | '/admin/kyc'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/deposit'
    | '/history'
    | '/orders'
    | '/p2p'
    | '/post-ad'
    | '/profile'
    | '/transfer'
    | '/wallet'
    | '/withdraw'
    | '/admin/kyc'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/deposit'
    | '/history'
    | '/orders'
    | '/p2p'
    | '/post-ad'
    | '/profile'
    | '/transfer'
    | '/wallet'
    | '/withdraw'
    | '/admin/kyc'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DepositRoute: typeof DepositRoute
  HistoryRoute: typeof HistoryRoute
  OrdersRoute: typeof OrdersRoute
  P2pRoute: typeof P2pRoute
  PostAdRoute: typeof PostAdRoute
  ProfileRoute: typeof ProfileRoute
  TransferRoute: typeof TransferRoute
  WalletRoute: typeof WalletRoute
  WithdrawRoute: typeof WithdrawRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-ad': {
      id: '/post-ad'
      path: '/post-ad'
      fullPath: '/post-ad'
      preLoaderRoute: typeof PostAdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2p': {
      id: '/p2p'
      path: '/p2p'
      fullPath: '/p2p'
      preLoaderRoute: typeof P2pRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DepositRoute: DepositRoute,
  HistoryRoute: HistoryRoute,
  OrdersRoute: OrdersRoute,
  P2pRoute: P2pRoute,
  PostAdRoute: PostAdRoute,
  ProfileRoute: ProfileRoute,
  TransferRoute: TransferRoute,
  WalletRoute: WalletRoute,
  WithdrawRoute: WithdrawRoute,
  AdminKycRoute: AdminKycRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
